### ISSUE TITLE
Can portions of the ontology be unobfuscated?

### ISSUE THREAD

**Issue by cmungall** [Sirius-sfi/aibel-mmd-ontology#1]
I am a developer on the [ENVO](http://obofoundry.org/ontology/envo) ontology and am interested in aligning MMD with ENVO. I heard about MMD via Ian Horrocks' talk. I am also generally interested in aligning design patterns between bio-ontologies and environment and energy ontologies.

The docs state:

> Aibel publishes the ontology with the primary intent of providing researchers and software developers with free access to a large-scale real industrial ontology and will therefore appreciate to be given access to or be made aware of any developments or new insights that result from the use of the ontology.

however, the use of obfuscated labels limits the uses beyond something like testing reasoners or tools that operate on structure. Is there a possibility in release sub-portions of the ontology unobfuscated?

If not, thank you for making the structure available

If it is of interest, structurally it looks similar to a lot of large bio-ontologies.

We are able to run our [relation graph](https://github.com/INCATools/relation-graph) reasoner on this quite easily, giving 19693709 entailed edges (direct and indirect; this doesn't use your universal axioms however)

And here is a result of running the [OAK](https://github.com/INCATools/ontology-access-kit/) `statistics` command if it is of interest:

```yaml
id: AllOntologies
ontologies:
- id: <http://example.com/Aibel/MMD#Z-ae1a9045fcbfd78349d5dc2e1ca18a619c0ff133f62e655ae6bf9aaa8565dc86>
was_generated_by:
  started_at_time: '2023-05-18T14:14:28.670722'
  was_associated_with: OAK
  acted_on_behalf_of: cjm
class_count: 202618
deprecated_class_count: 0
non_deprecated_class_count: 202618
class_count_with_text_definitions: 0
class_count_without_text_definitions: 202618
object_property_count: 212
annotation_property_count: 469
named_individual_count: 44561
subset_count: 0
rdf_triple_count: 5859907
subclass_of_axiom_count: 1120699
equivalent_classes_axiom_count: 1039
edge_count_by_predicate:
  <http://data.aibel.com/rdl/X101001912>:
    facet: <http://data.aibel.com/rdl/X101001912>
    filtered_count: 1
  <http://data.aibel.com/rdl/X101001932>:
    facet: <http://data.aibel.com/rdl/X101001932>
    filtered_count: 8
  <http://data.aibel.com/rdl/X101004953>:
    facet: <http://data.aibel.com/rdl/X101004953>
    filtered_count: 1422
  <http://data.aibel.com/rdl/X101004954>:
    facet: <http://data.aibel.com/rdl/X101004954>
    filtered_count: 814
  <http://data.aibel.com/rdl/X101004955>:
    facet: <http://data.aibel.com/rdl/X101004955>
    filtered_count: 29656
  <http://data.aibel.com/rdl/X101009258>:
    facet: <http://data.aibel.com/rdl/X101009258>
    filtered_count: 4346
  <http://data.aibel.com/rdl/X101009260>:
    facet: <http://data.aibel.com/rdl/X101009260>
    filtered_count: 1576
  <http://data.aibel.com/rdl/X101014372>:
    facet: <http://data.aibel.com/rdl/X101014372>
    filtered_count: 7
  <http://data.aibel.com/rdl/X101014800>:
    facet: <http://data.aibel.com/rdl/X101014800>
    filtered_count: 1
  <http://data.aibel.com/rdl/X101014801>:
    facet: <http://data.aibel.com/rdl/X101014801>
    filtered_count: 1
  <http://data.aibel.com/rdl/X101014825>:
    facet: <http://data.aibel.com/rdl/X101014825>
    filtered_count: 1
  <http://data.aibel.com/rdl/X101017798>:
    facet: <http://data.aibel.com/rdl/X101017798>
    filtered_count: 4
  <http://data.aibel.com/rdl/X101021646>:
    facet: <http://data.aibel.com/rdl/X101021646>
    filtered_count: 1733
  <http://data.aibel.com/rdl/X101021647>:
    facet: <http://data.aibel.com/rdl/X101021647>
    filtered_count: 41960
  <http://data.aibel.com/rdl/X101022434>:
    facet: <http://data.aibel.com/rdl/X101022434>
    filtered_count: 1
  <http://data.aibel.com/rdl/X101022478>:
    facet: <http://data.aibel.com/rdl/X101022478>
    filtered_count: 1
  <http://data.aibel.com/rdl/X101083548>:
    facet: <http://data.aibel.com/rdl/X101083548>
    filtered_count: 5
  <http://data.aibel.com/rdl/X101087190>:
    facet: <http://data.aibel.com/rdl/X101087190>
    filtered_count: 2499
  <http://data.aibel.com/rdl/X101100113>:
    facet: <http://data.aibel.com/rdl/X101100113>
    filtered_count: 23280
  <http://data.aibel.com/rdl/X101117458>:
    facet: <http://data.aibel.com/rdl/X101117458>
    filtered_count: 908
  <http://data.aibel.com/rdl/X101117459>:
    facet: <http://data.aibel.com/rdl/X101117459>
    filtered_count: 908
  <http://data.aibel.com/rdl/X101117460>:
    facet: <http://data.aibel.com/rdl/X101117460>
    filtered_count: 896
  <http://data.aibel.com/rdl/X101157663>:
    facet: <http://data.aibel.com/rdl/X101157663>
    filtered_count: 84
  <http://data.aibel.com/rdl/X101176390>:
    facet: <http://data.aibel.com/rdl/X101176390>
    filtered_count: 19
  <http://data.aibel.com/rdl/X101176392>:
    facet: <http://data.aibel.com/rdl/X101176392>
    filtered_count: 1
  <http://data.aibel.com/rdl/X101190745>:
    facet: <http://data.aibel.com/rdl/X101190745>
    filtered_count: 27
  <http://data.aibel.com/rdl/X101254493>:
    facet: <http://data.aibel.com/rdl/X101254493>
    filtered_count: 12
  <http://data.aibel.com/rdl/X101288652>:
    facet: <http://data.aibel.com/rdl/X101288652>
    filtered_count: 3
  <http://data.aibel.com/rdl/X101288654>:
    facet: <http://data.aibel.com/rdl/X101288654>
    filtered_count: 3
  <http://example.com/Aibel/MMD#Z-a9fb1e9d08dd81bb209d680618d9f2fae0396d5cbc6abb30d2b792a0ce4a7b64>:
    facet: <http://example.com/Aibel/MMD#Z-a9fb1e9d08dd81bb209d680618d9f2fae0396d5cbc6abb30d2b792a0ce4a7b64>
    filtered_count: 2
  <http://standards.iso.org/iso/15926/part14/arrangedPartOf>:
    facet: <http://standards.iso.org/iso/15926/part14/arrangedPartOf>
    filtered_count: 1
  <http://standards.iso.org/iso/15926/part14/datumUOM>:
    facet: <http://standards.iso.org/iso/15926/part14/datumUOM>
    filtered_count: 1
  <http://standards.iso.org/iso/15926/part14/datumValue>:
    facet: <http://standards.iso.org/iso/15926/part14/datumValue>
    filtered_count: 1
  <http://standards.iso.org/iso/15926/part14/featureOf>:
    facet: <http://standards.iso.org/iso/15926/part14/featureOf>
    filtered_count: 1
  <http://standards.iso.org/iso/15926/part14/functionalPartOf>:
    facet: <http://standards.iso.org/iso/15926/part14/functionalPartOf>
    filtered_count: 1
  <http://standards.iso.org/iso/15926/part14/hasFeature>:
    facet: <http://standards.iso.org/iso/15926/part14/hasFeature>
    filtered_count: 3210
  <http://standards.iso.org/iso/15926/part14/hasFunction>:
    facet: <http://standards.iso.org/iso/15926/part14/hasFunction>
    filtered_count: 1
  <http://standards.iso.org/iso/15926/part14/hasFunctionalPart>:
    facet: <http://standards.iso.org/iso/15926/part14/hasFunctionalPart>
    filtered_count: 1
  rdf:type:
    facet: rdf:type
    filtered_count: 27516
  rdfs:subClassOf:
    facet: rdfs:subClassOf
    filtered_count: 635903
  rdfs:subPropertyOf:
    facet: rdfs:subPropertyOf
    filtered_count: 1285
distinct_synonym_count: 8
synonym_statement_count: 8
synonym_statement_count_by_predicate:
  skos:altLabel:
    facet: skos:altLabel
    filtered_count: 8
mapping_statement_count_by_predicate:
  skos:exactMatch:
    facet: skos:exactMatch
    filtered_count: 0
mapping_statement_count_by_object_source:
  <http:
    facet: <http
    filtered_count: 23
mapping_statement_count_subject_by_object_source:
  <http:
    facet: <http
    filtered_count: 23
merged_class_query: 0
deprecated_property_count: 0
```
